config/routes.rb
Rails.application.routes.draw do

  resources :decks do
    resources :deck_cards, :only => [:index]
  end
  resources :deck_cards, :only => [:show, :create, :update, :destroy]

  resources :cards do
    collection do
        get 'search'
    end
  end
  root 'decks#index'

end

app/models/card.rb
class Card < ActiveRecord::Base
  VALID_COLORS = %w{
    Fire
    Water
    Wind
    Earth
    Ether
    Colorless
  }

  validates :color, inclusion: {in: Card::VALID_COLORS}
  def self.search_by_name(query)
    Card.where('lower(name) like lower(?)', "%#{query}%")
  end

  def self.sorted
    order(:card_type, :name)
  end
end

app/models/deck.rb
class Deck < ActiveRecord::Base
  has_many :deck_cards
  has_many :cards, :through => :deck_cards

  def number_of_copies_of(card)
    deck_cards.where(:card => card).sum(:amount)
  end
end

app/models/deck_card.rb
class DeckCard < ActiveRecord::Base
  belongs_to :deck
  belongs_to :card
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/cards_controller.rb
class CardsController < ApplicationController
  before_action :set_card, only: [:show, :edit, :update, :destroy]

  # GET /cards
  # GET /cards.json
  def index
    @color = card_params.fetch(:color, nil)
    @cards = Card.sorted.where(card_params)
  end

  # GET /cards/1
  # GET /cards/1.json
  def show
  end

  # GET /cards/new
  def new
    @card = Card.new
  end

  # GET /cards/1/edit
  def edit
  end

  # POST /cards
  # POST /cards.json
  def create
    @card = Card.new(card_params)

    respond_to do |format|
      if @card.save
        format.html { redirect_to @card, notice: 'Card was successfully created.' }
        format.json { render :show, status: :created, location: @card }
      else
        format.html { render :new }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /cards/1
  # PATCH/PUT /cards/1.json
  def update
    respond_to do |format|
      if @card.update(card_params)
        format.html { redirect_to @card, notice: 'Card was successfully updated.' }
        format.json { render :show, status: :ok, location: @card }
      else
        format.html { render :edit }
        format.json { render json: @card.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /cards/1
  # DELETE /cards/1.json
  def destroy
    @card.destroy
    respond_to do |format|
      format.html { redirect_to cards_url, notice: 'Card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def search
    if params[:query]
      @cards = Card.search_by_name(params[:query])
    else
      index
    end
    render :index
  end
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_card
      @card = Card.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def card_params
      params.fetch(:card, {}).permit(*whitelist)
    end

    def whitelist
      [:card_type, :cost, :rules_text, :power, :toughness, :rarity, :name, :color]
    end
end

app/controllers/deck_cards_controller.rb
class DeckCardsController < ApplicationController
    before_action :set_deck_card, only: [:update, :destroy, :show]

  def index
    @deck = Deck.includes(:deck_cards).includes(:cards).find(params[:deck_id])
    @deck_cards = @deck.deck_cards
  end

  def show
  end

  def create
    @deck_card = DeckCard.new(deck_card_params)
    respond_to do |format|
      if @deck_card.save
        format.html { redirect_to @deck_card, notice: 'Deck card was successfully created.' }
        format.json { render :show, status: :created, location: @deck_card }
      else
        format.html { render :new }
        format.json { render json: @deck_card.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @deck_card.update(deck_card_params.slice(:amount))
        format.html { redirect_to @deck_card, notice: 'Deck card was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck_card }
      else
        format.html { render :edit }
        format.json { render json: @deck_card.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @deck_card.destroy
    respond_to do |format|
      format.html { redirect_to deck_cards_url, notice: 'Deck card was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

    def set_deck_card
      @deck_card = DeckCard.find(params[:id])
    end


    def deck_card_params
      params.require(:deck_card).permit(:deck_id, :card_id, :amount)
    end
end

app/controllers/decks_controller.rb
class DecksController < ApplicationController
  before_action :set_deck, only: [:show, :edit, :update, :destroy]

  # GET /decks
  # GET /decks.json
  def index
    @decks = Deck.all
  end

  # GET /decks/1
  # GET /decks/1.json
  def show
  end

  # GET /decks/new
  def new
    @deck = Deck.new
  end

  # GET /decks/1/edit
  def edit
  end

  # POST /decks
  # POST /decks.json
  def create
    @deck = Deck.new(deck_params)

    respond_to do |format|
      if @deck.save
        format.html { redirect_to @deck, notice: 'Deck was successfully created.' }
        format.json { render :show, status: :created, location: @deck }
      else
        format.html { render :new }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /decks/1
  # PATCH/PUT /decks/1.json
  def update
    respond_to do |format|
      if @deck.update(deck_params)
        format.html { redirect_to @deck, notice: 'Deck was successfully updated.' }
        format.json { render :show, status: :ok, location: @deck }
      else
        format.html { render :edit }
        format.json { render json: @deck.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /decks/1
  # DELETE /decks/1.json
  def destroy
    @deck.destroy
    respond_to do |format|
      format.html { redirect_to decks_url, notice: 'Deck was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_deck
      @deck = Deck.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def deck_params
      params.require(:deck).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cards_helper.rb
module CardsHelper
  def cost_to_symbols(cost)
    cost.scan /\d+|Wi|Wa|Et|Ea|Fi|X/
  end
end

app/helpers/deck_cards_helper.rb
module DeckCardsHelper
end

app/helpers/decks_helper.rb
module DecksHelper
end

app/views/cards/_card.html.erb
<div class='card'>
  <div class='title-bar section'>
    <span> <%=card.name%></span>
  </div>
  <div>
    <div class='info-bar section'>
      <% if card.cost.present? %>
        <%- cost_to_symbols(card.cost).each do |symbol|%>
          <div class='mana-symbol'><%= symbol%></div>
        <%- end %>
      <% end %>
      <div class='power-toughness'>
        <% if card.power.present? %><div class='mana-symbol'><%=card.power%></div><%end%>
        <% if card.toughness.present? %><div class='mana-symbol'><%=card.toughness%></div><%end%>
      </div>
    </div>
    <div class='main section'>
      <div class='picture section'>
      </div>
      <div class='card-type'>
        <%=card.card_type%>
      </div>
      <div class='rules-text section'>
        <div>
          <%=card.rules_text%>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/cards/_form.html.erb
<%= form_for(@card) do |f| %>
  <% if @card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@card.errors.count, "error") %> prohibited this card from being saved:</h2>

      <ul>
      <% @card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :card_type %><br>
    <%= f.text_field :card_type %>
  </div>

  <div class="field">
    <%= f.label :color %><br>
    <%= f.select :color, options_for_select(Card::VALID_COLORS.map{|color| [color, color]})%>
  </div>

  <div class="field">
    <%= f.label :cost %><br>
    <%= f.text_field :cost %>
  </div>
  <div class="field">
    <%= f.label :rules_text %><br>
    <%= f.text_area :rules_text %>
  </div>
  <div class="field">
    <%= f.label :power %><br>
    <%= f.number_field :power %>
  </div>
  <div class="field">
    <%= f.label :toughness %><br>
    <%= f.number_field :toughness %>
  </div>
  <div class="field">
    <%= f.label :rarity %><br>
    <%= f.number_field :rarity %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/cards/edit.html.erb
<h1>Editing card</h1>

<%= render 'form' %>

<%= link_to 'Show', @card %> |
<%= link_to 'Back', cards_path %>

app/views/cards/index.html.erb
<%= link_to 'Make New Card', new_card_path %>
Quick Filters:
<ol>
  <li><%= link_to 'All Cards', cards_path %></li>
  <li><%= link_to 'Ether Cards', cards_path(:"card[color]" => 'Ether') %></li>
  <li><%= link_to 'Fire Cards', cards_path(:"card[color]" => 'Fire') %></li>
  <li><%= link_to 'Water Cards', cards_path(:"card[color]" => 'Water')%></li>
  <li><%= link_to 'Earth Cards', cards_path(:"card[color]" => 'Earth')%></li>
  <li><%= link_to 'Wind Cards', cards_path(:"card[color]" => 'Wind')%></li>
</ol>
<hr>

<h1><%= "Listing #{@color.present? ?  @color : 'all'} cards" %></h1>
* = no extra rules text

<table>
  <thead>
    <tr>
      <th>Name </th>
      <th>Card type</th>
      <th>Color</th>
      <th>Cost</th>
      <th>Power</th>
      <th>Toughness</th>
      <th>Rarity</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @cards.each do |card| %>
      <tr>
        <td><%= link_to "#{!card.rules_text.present? ? '*': ''}#{card.name}", card, :target => '_blank'%></td>
        <td><%= card.card_type %></td>
        <td><%= card.color %></td>
        <td><%= card.cost %></td>
        <td><%= card.power %></td>
        <td><%= card.toughness %></td>
        <td><%= card.rarity %></td>
        <td><%= link_to 'Edit', edit_card_path(card) %></td>
        <td><%= link_to 'Destroy', card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
  </table>
<br>

<% content_for :javascript_stuff do %>
<%end%>

app/views/cards/new.html.erb
<h1>New card</h1>

<%= render 'form' %>

<%= link_to 'Back', cards_path %>

app/views/cards/show.html.erb
<%= render 'card', :card => @card %>
<%= link_to 'Edit', edit_card_path(@card) %> |
<%= link_to 'Back', cards_path %>

app/views/deck_cards/_form.html.erb
<%= form_for(@deck_card) do |f| %>
  <% if @deck_card.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck_card.errors.count, "error") %> prohibited this deck_card from being saved:</h2>

      <ul>
      <% @deck_card.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :deck_id %><br>
    <%= f.number_field :deck_id %>
  </div>
  <div class="field">
    <%= f.label :card_id %><br>
    <%= f.number_field :card_id %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/deck_cards/edit.html.erb
<h1>Editing deck_card</h1>

<%= render 'form' %>

<%= link_to 'Show', @deck_card %> |
<%= link_to 'Back', deck_cards_path %>

app/views/deck_cards/index.html.erb
<h1>Listing deck_cards</h1>

<table>
  <thead>
    <tr>
      <th>Deck</th>
      <th>Card</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @deck_cards.each do |deck_card| %>
      <tr>
        <td><%= deck_card.deck_id %></td>
        <td><%= deck_card.card_id %></td>
        <td><%= link_to 'Destroy', deck_card, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

app/views/deck_cards/new.html.erb
<h1>New deck_card</h1>

<%= render 'form' %>

<%= link_to 'Back', deck_cards_path %>

app/views/deck_cards/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Deck:</strong>
  <%= @deck_card.deck_id %>
</p>

<p>
  <strong>Card:</strong>
  <%= @deck_card.card_id %>
</p>

<%= link_to 'Edit', edit_deck_card_path(@deck_card) %> |
<%= link_to 'Back', deck_cards_path %>

app/views/decks/_form.html.erb
<%= form_for(@deck) do |f| %>
  <% if @deck.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@deck.errors.count, "error") %> prohibited this deck from being saved:</h2>

      <ul>
      <% @deck.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/decks/edit.html.erb
<div class='row3'>
  <div class='column' id='search'></div>
  <div class='column' id='deck-list'></div>
  <div class='column' id='preview'></div>
</div>
<script type='text/x-handlebars-template' id="card-search-view">
  <div class='quick-search-wrap'>
    <div class='quick-search-toggle'>Quick Search&#8628;</div>
    <ul class='quick-search-filters' style='display:none'>
      <li data-color='Fire' class='Fire mana'></li>
      <li data-color='Water' class='Water mana'></li>
      <li data-color='Earth' class='Earth mana'></li>
      <li data-color='Wind' class='Wind mana'></li>
      <li data-color='Ether' class='Ether mana'></li>
    </ul>
  </div>
  <form action="<%= search_cards_path %>">
    <input type='text' name="query">
    <input type='submit' value='Search'>
  </form>
</script>

<script type='text/x-handlebars-template' id="card-search-item-view">
  <div>
    <span class='{{color}} mana'></span>
    <span class='name'>{{name}}</span>
    {{#if showCreatureStats}}<span>{{power}}/{{toughness}}</span>{{/if}}
    <span class='add-btn card-adjust-btn'>+</span>
  </div>
</script>

<script type='text/x-handlebars-template' id="card-search-results-view">

</script>

<script type='text/x-handlebars-template' id='deck-item-view'>
  <div><strong class='name'></strong><strong class='amount'></strong><div class='add-btn card-adjust-btn'>+</div><div class='remove-btn card-adjust-btn'>-</div></div>
</script>

<script type'text/x-handlebars-template' id='deck-list-view'>

</script>

<script type='text/x-handlebars-template' id="card-view">
  <div class='card'>
    <div class='title-bar section'>
      <span> {{name}}</span>
    </div>
    <div>
      <div class='info-bar section'>
        {{#each cost}}
          <div class='mana-symbol'>{{this}}</div>
        {{/each}}
        <div class='power-toughness'>
          <div class='mana-symbol'>{{power}}</div>
          <div class='mana-symbol'>{{toughness}}</div>
        </div>
      </div>
      <div class='main section'>
        <div class='picture section'>
        </div>
        <div class='card-type'>
          {{card_type}}
        </div>
        <div class='rules-text section'>
          <div>
            {{rules_text}}
          </div>
        </div>
        <div class='extra section'>
          <div class='mana-symbol rarity'>{{rarity}}</div>
        </div>
      </div>
    </div>
  </div>
</script>

<script type='text/javascript'>
  bootstrapped = {
    deckId: <%= @deck.id%>
  }
</script>

app/views/decks/index.html.erb
<h1>Listing decks</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="4"></th>
    </tr>
  </thead>

  <tbody>
    <% @decks.each do |deck| %>
      <tr>
        <td><%= deck.name %></td>
        <td><%= link_to 'Show', deck %></td>
        <td><%= link_to 'Printable', deck_path(deck, :print => 1)%></td>
        <td><%= link_to 'Edit', edit_deck_path(deck) %></td>
        <td><%= link_to 'Destroy', deck, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Deck', new_deck_path %>

app/views/decks/new.html.erb
<h1>New deck</h1>

<%= render 'form' %>

<%= link_to 'Back', decks_path %>

app/views/decks/show.html.erb
<p id="notice"><%= notice %></p>
  <strong>Name:</strong>
  <%= @deck.name %>
  <hr>
  <div class="<%= params[:print] ? 'plain': ''%>">
  <% count = 0%>
  <% @deck.deck_cards.each.with_index do |deck_card, index| %>
    <% deck_card.amount.times do %>
      <%= render('cards/card', :card => deck_card.card) %>
      <% count += 1 %>
      <% if count % 9 == 0 %>
        <div class="page-break"></div>
      <% end %>
    <%end%>
  <%end%>
  <div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <%= javascript_include_tag 'pace.min'%>
  <title>CardGame</title>

  <%= stylesheet_link_tag    'application', media: 'all'%>
  <%= csrf_meta_tags %>
</head>
<body>
  <div id='main'>
    <ul id='nav'>
      <li><%= link_to 'Decks', decks_path %></li>
      <li><%= link_to 'Cards', cards_path %></li>
    </ul>
    <hr style='clear:both'>
    <%= yield %>
  </div>
  <%= javascript_include_tag 'application'%>
  <%= yield :javascript_stuff%>
</body>
</html>